
import { Festival, SecurityType } from './types';

export const FESTIVALS: Festival[] = [
  {
    id: "jan-1",
    month: 1,
    name: "元旦 & 臘八節",
    date2025: "1月1日 / 1月6日",
    lunarDate: "十二月初一 / 十二月初八",
    intro: "元旦標誌著新年的開始；臘八節則是祭祀祖先、祈求豐收的傳統節慶，品嚐臘八粥象徵溫暖與和諧。",
    securityPoint: "民俗文化是民族根基，守護節日傳統即是守護民族精神的開端。",
    securityType: SecurityType.CULTURAL,
    aiPrompt: "A cozy traditional Chinese kitchen scene, a large steaming pot of Laba congee (臘八粥), traditional red lanterns, warm atmosphere, soft lighting, watercolor style, representing the start of cultural heritage.",
    color: "bg-red-50"
  },
  {
    id: "feb-1",
    month: 2,
    name: "春節 & 元宵節",
    date2025: "1月29日 / 2月12日",
    lunarDate: "正月初一 / 正月十五",
    intro: "中華民族最重要的節日，象徵萬象更新、闔家團圓。元宵節則是慶祝團圓的延續。",
    securityPoint: "【文化安全的核心】。家國情懷是文化认同的基石，防範文化侵蝕，增強文化自信。",
    securityType: SecurityType.CULTURAL,
    aiPrompt: "A magnificent Chinese family reunion dinner, red envelopes (hongbao), fireworks over a traditional village, vibrant red and gold theme, oil painting style, atmosphere of prosperity and cultural unity.",
    color: "bg-red-100"
  },
  {
    id: "mar-1",
    month: 3,
    name: "驚蟄 & 植樹節",
    date2025: "3月5日 / 3月12日",
    lunarDate: "二月初六 / 二月十三",
    intro: "驚蟄時節春雷動，萬物生機勃勃；植樹節鼓勵公民參與綠化，改善生態環境。",
    securityPoint: "【生態安全】。護林保土是國土安全的基礎，青山綠水就是金山銀山。",
    securityType: SecurityType.ECOLOGICAL,
    aiPrompt: "Vibrant green landscape of hills with students planting saplings, a small sprout breaking through the soil, morning dew, spring sunlight, cinematic nature photography style, emphasizing ecological preservation.",
    color: "bg-green-50"
  },
  {
    id: "apr-1",
    month: 4,
    name: "清明節 & 4.15 全民國家安全教育日",
    date2025: "4月4日 / 4月15日",
    lunarDate: "三月初七",
    intro: "清明祭祖體現孝親與懷念先烈；4.15 旨在增進全民國家安全意識。",
    securityPoint: "【領土安全與國安法】。祭奠先烈，提醒我們守護來之不易的領土主權，推廣國安意識。",
    securityType: SecurityType.TERRITORIAL,
    aiPrompt: "A solemn memorial park with white chrysanthemums, a silhouette of a historical monument, clean blue sky, a digital shield graphic representing security, respectful and majestic atmosphere, digital art style.",
    color: "bg-blue-50"
  },
  {
    id: "apr-2",
    month: 4,
    name: "中國航天日 (4.24)",
    date2025: "4月24日",
    lunarDate: "三月廿七",
    intro: "紀念中國第一顆人造衛星發射成功，激勵年輕一代探索太空、熱愛科學。",
    securityPoint: "【科技安全】。星辰大海的探索體現國家硬實力，掌握核心技術是國家安全的關鍵。",
    securityType: SecurityType.TECHNOLOGICAL,
    aiPrompt: "A sleek Chinese spacecraft ascending towards the stars, the Shenzhou capsule, moon and mars in background, high-tech aesthetics, futuristic style, blue and silver lighting, emphasizing technological leap.",
    color: "bg-indigo-50"
  },
  {
    id: "may-1",
    month: 5,
    name: "勞動節 & 五四青年節",
    date2025: "5月1日 / 5月4日",
    lunarDate: "四月初四 / 四月初七",
    intro: "讚美勞動者的辛勤與五四青年追求進步、民主與科學的精神。",
    securityPoint: "【社會安全】。勞動創造價值，奮鬥成就夢想，社會穩定來自全民的拼搏精神。",
    securityType: SecurityType.SOCIAL,
    aiPrompt: "Dynamic collage of energetic young students and workers in diverse fields (tech, farming, medical), sun rising behind them, poster design style, bold colors, inspiring and heroic atmosphere.",
    color: "bg-orange-50"
  },
  {
    id: "jun-1",
    month: 6,
    name: "端午節",
    date2025: "5月31日(假) / 6月20日",
    lunarDate: "五月初五",
    intro: "紀念愛國詩人屈原，包含賽龍舟、食粽子等習俗，展現民族脊樑。",
    securityPoint: "【文化安全】。愛國主義是民族魂，傳承屈原精神，守護民族的歷史記憶。",
    securityType: SecurityType.CULTURAL,
    aiPrompt: "A powerful dragon boat race on a mist-covered river, dynamic water splashes, traditional zongzi wrapped in bamboo leaves, ink wash painting style mixed with modern realism, symbolizing patriotic spirit.",
    color: "bg-emerald-50"
  },
  {
    id: "jul-1",
    month: 7,
    name: "建黨紀念日 & 香港回歸紀念日",
    date2025: "7月1日",
    lunarDate: "六月初七",
    intro: "慶祝香港回歸祖國，展現一國兩制的成功實踐與國家統一的決心。",
    securityPoint: "【政治安全】。維護國家主權與統一，政治安全是所有發展的前提。",
    securityType: SecurityType.POLITICAL,
    aiPrompt: "Victoria Harbour skyline at sunrise, the golden Bauhinia flower monument, national flag and HKSAR flag flying high, cinematic city lighting, photography style, symbolizing unity and sovereignty.",
    color: "bg-red-50"
  },
  {
    id: "aug-1",
    month: 8,
    name: "建軍節 (8.1)",
    date2025: "8月1日",
    lunarDate: "六月初八",
    intro: "紀念中國人民解放軍成立，向守衛國家的軍人致敬。",
    securityPoint: "【軍事安全】。保家衛國的鋼鐵長城，強大的軍隊是和平的守護者。",
    securityType: SecurityType.MILITARY,
    aiPrompt: "A row of disciplined soldiers in modern uniform, background with aircraft and ships, dramatic light, realistic oil painting style, representing a powerful and protective military force.",
    color: "bg-stone-100"
  },
  {
    id: "sep-1",
    month: 9,
    name: "抗日戰爭勝利紀念日 (9.3)",
    date2025: "9月3日",
    lunarDate: "七月十一",
    intro: "緬懷抗戰英烈，牢記歷史，反思戰爭，祈願持久和平。",
    securityPoint: "【歷史教育】。勿忘國恥，警惕外來侵略威脅，歷史的記憶是安全的警醒。",
    securityType: SecurityType.TERRITORIAL,
    aiPrompt: "A peaceful scene of doves flying over a historical Great Wall, sunlight breaking through clouds, solemn black and white ink elements with subtle gold accents, concept of peace through strength.",
    color: "bg-slate-100"
  },
  {
    id: "sep-2",
    month: 9,
    name: "中國農民豐收節",
    date2025: "9月22日 (秋分)",
    lunarDate: "八月初一",
    intro: "為農民設立的節日，展示中國農業的發展成就與收穫喜悅。",
    securityPoint: "【糧食安全】。手中有糧，心中不慌。守住 18 億畝耕地紅線是國家命脈。",
    securityType: SecurityType.FOOD,
    aiPrompt: "A breathtaking wide shot of a golden rice field in China, traditional red banners saying 'Harvest Festival', a modern harvester working alongside happy farmers, sunny sky, oil painting style, emphasizing abundance.",
    color: "bg-yellow-50"
  },
  {
    id: "sep-3",
    month: 9,
    name: "中秋節",
    date2025: "10月6日(假)",
    lunarDate: "八月十五",
    intro: "團圓、賞月、食月餅，象徵美滿與思鄉之情。",
    securityPoint: "【文化安全】。團圓文化加強了民族凝聚力，是維護國家統一的柔性力量。",
    securityType: SecurityType.CULTURAL,
    aiPrompt: "A bright full moon over a traditional garden pavilion, families sharing mooncakes, warm yellow lights from lanterns, fantasy digital art style, dreaming of peace and unity.",
    color: "bg-amber-50"
  },
  {
    id: "oct-1",
    month: 10,
    name: "國慶節 (10.1)",
    date2025: "10月1日",
    lunarDate: "八月初十",
    intro: "慶祝中華人民共和國成立，展現國家發展進步的偉大成就。",
    securityPoint: "【政治安全】。最高規格的愛國主義教育，展現大國氣象，鞏固國本。",
    securityType: SecurityType.POLITICAL,
    aiPrompt: "Tiananmen Square decorated with massive flower displays, red flags waving, blue sky, wide angle shot, grand and festive atmosphere, photorealistic style.",
    color: "bg-red-50"
  },
  {
    id: "oct-2",
    month: 10,
    name: "重陽節",
    date2025: "10月29日",
    lunarDate: "九月初九",
    intro: "登高望遠、賞菊，敬老尊賢的傳統美德節日。",
    securityPoint: "【社會安全】。尊老愛老的優良傳統是社會穩定、家庭和睦的安全閥。",
    securityType: SecurityType.SOCIAL,
    aiPrompt: "Elderly people and children climbing a scenic autumn mountain, golden chrysanthemum flowers everywhere, warm setting sun, soft colors, serene and heartwarming painting style.",
    color: "bg-orange-50"
  },
  {
    id: "nov-1",
    month: 11,
    name: "消防安全教育日 (11.9)",
    date2025: "11月9日",
    lunarDate: "十月十九",
    intro: "普及消防安全知識，增強防火、滅火和自我保護能力。",
    securityPoint: "【公共安全】。生命至上，預防為主，公共安全是每個公民的責任。",
    securityType: SecurityType.PUBLIC,
    aiPrompt: "Brave firefighters in action with modern equipment, a shield symbol composed of water droplets, city safety icons, bright heroic lighting, semi-realistic illustration style.",
    color: "bg-red-50"
  },
  {
    id: "dec-1",
    month: 12,
    name: "國家憲法日 (12.4)",
    date2025: "12月4日",
    lunarDate: "十一月十四",
    intro: "憲法是國家的根本大法，維護憲法權威即維護國法尊嚴。",
    securityPoint: "【法治安全】。維護國安法與憲法權威，法治是國家長治久安的保障。",
    securityType: SecurityType.LEGAL,
    aiPrompt: "The Constitution of China book placed on a mahogany desk with a gavel, background with scales of justice, dignified atmosphere, warm studio lighting, photography style.",
    color: "bg-slate-50"
  },
  {
    id: "dec-2",
    month: 12,
    name: "南京大屠殺死難者國家公祭日 (12.13)",
    date2025: "12月13日",
    lunarDate: "十一月廿三",
    intro: "哀悼大屠殺死難者，警示世人反對戰爭、珍愛和平。",
    securityPoint: "【國土安全】。警鐘長鳴，強大的國土安全屏障才能防止悲劇重演。",
    securityType: SecurityType.TERRITORIAL,
    aiPrompt: "A single lit candle in a dark solemn space, silhouettes of people in silent mourning, cold winter atmosphere, minimal artistic style, focusing on remembrance and dignity.",
    color: "bg-zinc-100"
  },
  {
    id: "dec-3",
    month: 12,
    name: "冬至",
    date2025: "12月21日",
    lunarDate: "十一月初一",
    intro: "二十四節氣中重要的一環，象徵陽氣回升，有食餃子或湯圓的習俗。",
    securityPoint: "【傳統節氣文化】。認識自然規律，傳承華夏智慧，體現文化韌性。",
    securityType: SecurityType.CULTURAL,
    aiPrompt: "A plate of steaming dumplings and tangyuan on a wooden table, snowy window in background, cozy home lighting, realistic digital art, warm winter vibes.",
    color: "bg-blue-50"
  }
];
